# Placeholder content generators. These are intentionally minimal for now.

# template_stack <name> <description> [unit]...
template_stack() {
  local name="$1" description="$2"
  shift 2

  cat <<EOF
# Stack: ${name}
# ${description}
#
# Placeholder stack definition generated by st8atlas.

# Pulls in the root configuration of the level above, which itself chains upwards.
locals {
  root = read_terragrunt_config(find_in_parent_folders("root.hcl"))
}
EOF

  if [[ $# -eq 0 ]]; then
    cat <<EOF

# No units selected. Run 'st8atlas stack units --name ${name}' to select some.
EOF
    return 0
  fi

  local unit
  for unit in "$@"; do
    cat <<EOF

unit "${unit}" {
  source = "\${get_repo_root()}/units/${unit}"
  path   = "${unit}"
}
EOF
  done
}

template_unit() {
  local name="$1" description="$2"
  cat <<EOF
# Unit: ${name}
# ${description}
#
# Placeholder unit definition generated by st8atlas.

terraform {
  source = "\${get_repo_root()}/modules/${name}"
}

inputs = {
  name = "${name}"
}
EOF
}

template_module_main() {
  local name="$1" description="$2"
  cat <<EOF
# Module: ${name}
# ${description}
#
# Placeholder module generated by st8atlas.

terraform {
  required_version = ">= 1.5.0"
}
EOF
}

template_module_variables() {
  local name="$1"
  cat <<EOF
variable "name" {
  description = "Name of the ${name} unit."
  type        = string
  default     = "${name}"
}
EOF
}

template_module_outputs() {
  cat <<'EOF'
output "name" {
  description = "Name of the unit."
  value       = var.name
}
EOF
}

template_gitignore() {
  cat <<'EOF'
.terraform/
.terragrunt-cache/
*.tfstate
*.tfstate.backup
.terraform.lock.hcl
EOF
}

# template_root_terragrunt <inherit-parent>
template_root_terragrunt() {
  local inherit_parent="${1:-false}"

  cat <<'EOF'
# Root terragrunt configuration generated by st8atlas.
# Placeholder content - configure your remote state and providers here.
EOF

  if [[ "$inherit_parent" == "true" ]]; then
    # find_in_parent_folders starts one level up, so this chains through every
    # root.hcl above this one.
    cat <<'EOF'

locals {
  parent  = read_terragrunt_config(find_in_parent_folders("root.hcl"))
  project = local.parent.locals.project
}
EOF
  else
    cat <<'EOF'

locals {
  project = "st8atlas"
}
EOF
  fi
}
