cost_desc() {
  usage_entry "  " "cost <capability>" "Generate stack costs with c3x."
}

cost_usage() {
  usage_title "$(basename "$0") cost <capability> [args...]"
  usage_summary "Generate cost estimates with c3x. A usage configuration is added to every new stack."
  usage_section "Capabilities:"
  usage_entry "  ├─" "report [args...]" "Generate the cost report for a stack"
  usage_argument "  │  └─" "--name <name>" "Name of the stack (required)"
  usage_entry "  └─" "sync" "Add the usage configuration to every stack that lacks one"
}

COST_USAGE_FILE_NAME="c3x-usage.yml"

cost_template_usage() {
  local name="$1"
  cat <<EOF
# c3x usage configuration for stack '${name}'.
# Placeholder content generated by the st8atlas cost extension.
#
# Add runtime quantities per resource, for example:
#   resource_usage:
#     aws_s3_bucket.assets:
#       monthly_storage_gb: 100
#       monthly_requests: 10000
version: 0.1

resource_usage: {}
EOF
}

cost_write_usage() {
  local name="$1" directory="$2"
  local file="${directory}/${COST_USAGE_FILE_NAME}"

  [[ -e "$file" ]] && return 1

  mkdir -p "$directory"
  cost_template_usage "$name" > "$file"
  return 0
}

# Called by the core whenever a stack is created.
cost_hook_stack_created() {
  local name="$1" directory="$2"
  if cost_write_usage "$name" "$directory"; then
    log_info "Added c3x usage configuration '${COST_USAGE_FILE_NAME}'."
  fi
}

cost_report() {
  parse_options "$@"
  require_option "$ARG_NAME" "--name"
  stack_require_existing "$ARG_NAME"
  ensure_command c3x "Install c3x to generate cost estimates."

  local directory stack_file usage_file
  directory="$(stack_directory "$ARG_NAME")"
  stack_file="${directory}/${STACK_FILE_NAME}"
  cost_write_usage "$ARG_NAME" "$directory" || true
  usage_file="${directory}/${COST_USAGE_FILE_NAME}"

  local units=() unit
  while IFS= read -r unit; do
    [[ -n "$unit" ]] || continue
    units+=("$unit")
  done < <(stack_unit_names "$stack_file")

  [[ ${#units[@]} -gt 0 ]] \
    || die "Stack '${ARG_NAME}' has no units. Add some with '$(basename "$0") stack units --name ${ARG_NAME}'."

  # c3x reads Terraform, so the estimate runs against the module behind every unit.
  local module_directory
  for unit in "${units[@]}"; do
    module_directory="${ST8_PROJECT_ROOT}/${MODULES_DIR_NAME}/${unit}"
    if [[ ! -d "$module_directory" ]]; then
      log_warn "Unit '${unit}' has no module at '${MODULES_DIR_NAME}/${unit}', skipping."
      continue
    fi

    log_info "Estimating unit '${unit}'."
    c3x estimate --path "$module_directory" --usage "$usage_file"
  done
}

cost_sync() {
  [[ $# -eq 0 ]] || die "'sync' does not take any arguments."

  local name path added=0
  while IFS='|' read -r _ name path _; do
    [[ -n "$name" ]] || continue
    if cost_write_usage "$name" "${ST8_PROJECT_ROOT}/${path}"; then
      log_info "Added '${COST_USAGE_FILE_NAME}' to stack '${name}'."
      added=$((added + 1))
    fi
  done < <(state_records "stack")

  log_info "Usage configurations synchronized, ${added} added."
}

cost_main() {
  [[ $# -lt 1 ]] && { cost_usage; exit 1; }

  local capability="$1"
  shift

  case "$capability" in
    -h|--help)
      cost_usage
      ;;
    report)
      require_project
      cost_report "$@"
      ;;
    sync)
      require_project
      cost_sync "$@"
      ;;
    *)
      log_error "Unknown capability '${capability}'."
      cost_usage
      exit 1
      ;;
  esac
}
