cost_desc() {
  usage_entry "  " "cost <capability>" "Generate stack costs with c3x."
}

cost_usage() {
  usage_title "$(basename "$0") cost <capability> [args...]"
  usage_summary "Generate cost estimates with c3x. A usage configuration is added to every new stack."
  usage_section "Capabilities:"
  usage_entry "  ├─" "report [args...]" "Write the markdown cost breakdown of a stack"
  usage_argument "  │  ├─" "--name <name>" "Name of the stack (required)"
  usage_argument "  │  └─" "--output <file>" "Write the report here instead of stdout"
  usage_entry "  └─" "sync" "Add the usage configuration to every stack that lacks one"
}

COST_USAGE_FILE_NAME="c3x-usage.yml"

cost_template_usage() {
  local name="$1"
  cat <<EOF
# c3x usage configuration for stack '${name}'.
# Placeholder content generated by the st8atlas cost extension.
#
# Add runtime quantities per resource, for example:
#   resource_usage:
#     aws_s3_bucket.assets:
#       monthly_storage_gb: 100
#       monthly_requests: 10000
version: 0.1

resource_usage: {}
EOF
}

cost_write_usage() {
  local name="$1" directory="$2"
  local file="${directory}/${COST_USAGE_FILE_NAME}"

  [[ -e "$file" ]] && return 1

  mkdir -p "$directory"
  cost_template_usage "$name" > "$file"
  return 0
}

# Called by the core whenever a stack is created.
cost_hook_stack_created() {
  local name="$1" directory="$2"
  if cost_write_usage "$name" "$directory"; then
    log_info "Added c3x usage configuration '${COST_USAGE_FILE_NAME}'."
  fi
}

cost_report() {
  parse_options "$@"
  require_option "$ARG_NAME" "--name"
  stack_require_existing "$ARG_NAME"
  ensure_command c3x "Install c3x to generate cost estimates."

  if [[ -n "$ARG_OUTPUT" ]]; then
    cost_markdown "$ARG_NAME" > "$ARG_OUTPUT"
    log_info "Wrote cost report '${ARG_OUTPUT}'."
  else
    cost_markdown "$ARG_NAME"
  fi
}

# Renders the cost breakdown of a stack as markdown, one section per unit.
cost_markdown() {
  local name="$1"

  local directory stack_file usage_file
  directory="$(stack_directory "$name")"
  stack_file="${directory}/${STACK_FILE_NAME}"
  cost_write_usage "$name" "$directory" || true
  usage_file="${directory}/${COST_USAGE_FILE_NAME}"

  local units=() unit
  while IFS= read -r unit; do
    [[ -n "$unit" ]] || continue
    units+=("$unit")
  done < <(stack_unit_names "$stack_file")

  echo "# Cost breakdown: ${name}"
  echo ""

  if [[ ${#units[@]} -eq 0 ]]; then
    echo "_The stack has no units._"
    return 0
  fi

  echo "| Unit | Module | Estimated |"
  echo "| --- | --- | :---: |"
  local module_directory
  for unit in "${units[@]}"; do
    module_directory="${MODULES_DIR_NAME}/${unit}"
    if [[ -d "${ST8_PROJECT_ROOT}/${module_directory}" ]]; then
      echo "| \`${unit}\` | \`${module_directory}\` | yes |"
    else
      echo "| \`${unit}\` | _missing_ | no |"
    fi
  done
  echo ""

  # c3x reads Terraform, so the estimate runs against the module behind every unit.
  for unit in "${units[@]}"; do
    echo "## Unit \`${unit}\`"
    echo ""

    module_directory="${ST8_PROJECT_ROOT}/${MODULES_DIR_NAME}/${unit}"
    if [[ ! -d "$module_directory" ]]; then
      echo "_No module at \`${MODULES_DIR_NAME}/${unit}\`, skipped._"
      echo ""
      continue
    fi

    # c3x emits its own '## c3x estimate' heading, demote it below the unit heading.
    c3x estimate --format markdown --path "$module_directory" --usage "$usage_file" 2>&1 \
      | sed 's/^#/##/' \
      || echo "_c3x failed for this unit._"
    echo ""
  done
}

# Renders the cost breakdown of a stack as JSON, for the machine readable snapshot.
cost_json() {
  local name="$1"

  local directory stack_file usage_file
  directory="$(stack_directory "$name")"
  stack_file="${directory}/${STACK_FILE_NAME}"
  cost_write_usage "$name" "$directory" || true
  usage_file="${directory}/${COST_USAGE_FILE_NAME}"

  local units=() unit
  while IFS= read -r unit; do
    [[ -n "$unit" ]] || continue
    units+=("$unit")
  done < <(stack_unit_names "$stack_file")

  echo "{"
  echo "  \"stack\": \"${name}\","
  echo "  \"units\": ["

  local module_directory estimate
  local index=0 last=$(( ${#units[@]} - 1 ))
  for unit in "${units[@]}"; do
    module_directory="${ST8_PROJECT_ROOT}/${MODULES_DIR_NAME}/${unit}"

    echo "    {"
    echo "      \"unit\": \"${unit}\","
    echo "      \"module\": \"${MODULES_DIR_NAME}/${unit}\","

    if [[ ! -d "$module_directory" ]]; then
      echo "      \"error\": \"no module at ${MODULES_DIR_NAME}/${unit}\","
      echo "      \"estimate\": null"
    elif estimate="$(c3x estimate --format json --path "$module_directory" --usage "$usage_file" 2> /dev/null)"; then
      echo "      \"estimate\":"
      echo "$estimate" | sed 's/^/      /'
    else
      echo "      \"error\": \"c3x failed\","
      echo "      \"estimate\": null"
    fi

    if [[ $index -lt $last ]]; then
      echo "    },"
    else
      echo "    }"
    fi
    index=$((index + 1))
  done

  echo "  ]"
  echo "}"
}

# Contributes the machine readable cost breakdown to the stack snapshot.
cost_hook_snapshot() {
  local name="$1"
  echo "[cost]"
  if command -v c3x > /dev/null 2>&1; then
    cost_json "$name"
  else
    echo "{ \"stack\": \"${name}\", \"error\": \"c3x is not installed\", \"units\": [] }"
  fi
  echo ""
}

cost_sync() {
  [[ $# -eq 0 ]] || die "'sync' does not take any arguments."

  local name path added=0
  while IFS='|' read -r _ name path _; do
    [[ -n "$name" ]] || continue
    if cost_write_usage "$name" "${ST8_PROJECT_ROOT}/${path}"; then
      log_info "Added '${COST_USAGE_FILE_NAME}' to stack '${name}'."
      added=$((added + 1))
    fi
  done < <(state_records "stack")

  log_info "Usage configurations synchronized, ${added} added."
}

cost_main() {
  [[ $# -lt 1 ]] && { cost_usage; exit 1; }

  local capability="$1"
  shift

  case "$capability" in
    -h|--help)
      cost_usage
      ;;
    report)
      require_project
      cost_report "$@"
      ;;
    sync)
      require_project
      cost_sync "$@"
      ;;
    *)
      log_error "Unknown capability '${capability}'."
      cost_usage
      exit 1
      ;;
  esac
}
